/**
 * A machine coming in: it asks, a person answers, it collects.
 *
 * Both ends in one file because they are one conversation with a gap in the middle. The machine's
 * two calls need no session — one because a machine nobody has approved has no identity to prove,
 * the other because the secret handed back at the asking *is* the proof. The person's four need
 * a session. The machine calls never name a Space. A person's approval may carry the Space whose
 * Add machine journey opened the page, but that is browser intent, not a choice delegated to the
 * unapproved machine.
 */

import { z } from '@hono/zod-openapi'
import type { Database } from '../db/connection.ts'
import {
  approveEnrolment,
  collectEnrolment,
  enrolmentWaiting,
  existingMachinesFor,
  openEnrolment,
  refuseEnrolment,
} from '../db/enrolment.ts'
import { spacesOf } from '../db/space.ts'
import { AGENT_COMMANDS } from '../machine/agent-kind.ts'
import { POLL_SECONDS } from '../machine/presence.ts'
import { newEnrolmentSecret } from '../machine/secret.ts'
import { newUserCode, readUserCode } from '../machine/user-code.ts'
import { onTheWire, Presence } from '../machine/whereabouts.ts'
import { hashSecret } from '../secret.ts'
import { type Failure, refused } from './failure.ts'
import { aPerson, anyone, named, nothing, refuses, sends } from './route.ts'

export type EnrolmentApi = {
  readonly db: Database
  /** Where the person doing the approving is sent. Printed by the machine, opened by them. */
  readonly webOrigin: string
}

const AskToConnect = named('AskToConnect', {
  machineName: z.string().min(1).max(200).openapi({ example: 'mina-mbp' }),
})

const AskedToConnect = named('AskedToConnect', {
  /**
   * What this machine shows to collect its credential. Handed back once, here, so it never has
   * to be stored anywhere before it is worth anything.
   */
  secret: z.string(),
  userCode: z.string().openapi({ example: 'WDJB-MJHT' }),
  /** Where to go and type it. Short, because somebody may be typing it on a phone. */
  verifyUrl: z.url(),
  /** The same page with the code already in it, for anyone who can click rather than type. */
  verifyUrlComplete: z.url(),
  pollSeconds: z.number().int().positive(),
  expiresAt: z.iso.datetime(),
})

const CollectEnrolment = named('CollectEnrolment', {
  secret: z.string().min(1).max(200),
  /** What this machine calls itself. Used only when nobody named it at approval. */
  machineName: z.string().min(1).max(200).openapi({ example: 'build-server-1' }),
  /**
   * The credential this machine will hold, minted by the machine itself.
   *
   * Made here rather than here-and-handed-back for one reason: the answer to this call can be
   * lost. Generated by the server, the plaintext existed once, in that one response — and a
   * machine that never received it could only ask again and be told the enrolment was spent,
   * leaving an offline machine in somebody's Space that nobody could ever recover.
   *
   * Held by the machine, asking again is the same machine asking again, and the answer it missed
   * is still true. Only its hash is stored, exactly as before.
   */
  token: z.string().min(32).max(200),
})

const Collected = z
  .discriminatedUnion('kind', [
    z.object({
      kind: z.literal('granted'),
      machineId: z.uuid(),
      /** So a machine knows what to look for before its first check-in, not 25 seconds after. */
      lookFor: z.array(z.string()).readonly(),
    }),
    z.object({ kind: z.literal('waiting') }),
    z.object({ kind: z.literal('refused') }),
    z.object({ kind: z.literal('expired') }),
    z.object({ kind: z.literal('spent') }),
    z.object({ kind: z.literal('no-enrolment') }),
  ])
  .openapi('Collected')

const LetItIn = named('LetItIn', {
  userCode: z.string().max(64),
  /** Present only when the person explicitly chose an existing same-named identity. */
  replaceMachineId: z.uuid().optional(),
  /** Present when this approval began from one Space's Add machine journey. */
  spaceSlug: z.string().optional(),
})

/** No enrolment is waiting under that code: never was, already answered, or ran out. */
const NOT_WAITING: Failure<404> = { reason: 'no-enrolment', recovery: 'start-over', status: 404 }

/** Said the same way by all four routes, because all four mean it the same way. */
const NOTHING_IS_WAITING = refuses(NOT_WAITING, 'Nothing is waiting under that code')

const CANNOT_REPLACE: Failure<404> = {
  reason: 'machine-unavailable',
  recovery: 'start-over',
  status: 404,
}

const ExistingMachine = named('ExistingMachine', {
  id: z.uuid(),
  createdAt: z.iso.datetime(),
  presence: Presence,
})

const Waiting = named('MachineWaiting', {
  machineName: z.string(),
  expiresAt: z.iso.datetime(),
  existingMachines: z.array(ExistingMachine).readonly(),
})

/** Shown once. Only its hash is kept, so this is the only moment it can be read. */
const Key = named('MachineKey', { key: z.string(), expiresAt: z.iso.datetime() })

export function enrolmentApi(deps: EnrolmentApi) {
  return [
    askingToConnect(deps),
    collecting(deps),
    whatIsWaiting(deps),
    refusing(deps),
    approving(deps),
    makingAKey(deps),
  ]
}

/** Asking to come in, which produces a code somebody has to say yes to. */
function askingToConnect({ db, webOrigin }: EnrolmentApi) {
  return anyone().post('/enrolments', {
    summary: 'Ask to bring this machine in, and get a code for somebody to approve',
    body: AskToConnect,
    answers: { 201: sends(AskedToConnect, 'Show the code and start asking') },

    run: async (c) => {
      const secret = newEnrolmentSecret()
      const userCode = newUserCode()

      const opened = await openEnrolment(db, {
        kind: 'asking',
        machineName: c.req.valid('json').machineName,
        secretHash: secret.hash,
        userCode,
      })

      return c.json(
        {
          secret: secret.secret,
          userCode,
          verifyUrl: `${webOrigin}/connect`,
          verifyUrlComplete: `${webOrigin}/connect/${userCode}`,
          pollSeconds: POLL_SECONDS,
          expiresAt: opened.expiresAt.toISOString(),
        },
        201,
      )
    },
  })
}

/**
 * Collecting the credential, which is also how a machine asks whether it has been approved yet.
 *
 * The one verb left in this API, and it stays. What it does is exchange one secret for another,
 * which is the shape every token endpoint has — and the noun-ish alternative, a session under
 * `/machines/current/…`, would put a route there that nothing can hold a machine credential for
 * yet. That path means "a machine talking about itself" and every route under it is behind a
 * machine's own credential, with a test that says so and no exceptions. A rule with an exception
 * in it is worth less than this name is worth.
 */
function collecting({ db }: EnrolmentApi) {
  return anyone().post('/enrolments/collect', {
    summary: 'Collect the credential this enrolment was approved for',
    body: CollectEnrolment,
    answers: { 200: sends(Collected, 'What became of it, including still waiting') },

    run: async (c) => {
      const asked = c.req.valid('json')
      const collected = await collectEnrolment(db, {
        secretHash: hashSecret(asked.secret),
        tokenHash: hashSecret(asked.token),
        machineName: asked.machineName,
      })

      if (collected.kind === 'granted') {
        return c.json(
          { kind: 'granted' as const, machineId: collected.machineId, lookFor: AGENT_COMMANDS },
          200,
        )
      }

      // Still waiting is one of these, and the most common. It is not a failure, so it is not a
      // failure status — the machine reads the kind and decides whether to ask again.
      return c.json({ kind: collected.kind }, 200)
    },
  })
}

/** Looking at a machine before answering it. */
function whatIsWaiting({ db }: EnrolmentApi) {
  return aPerson(db).get('/enrolments/{userCode}', {
    summary: 'What is asking to come in under this code',
    params: { userCode: z.string() },
    answers: { 200: sends(Waiting, 'A machine is waiting on an answer'), 404: NOTHING_IS_WAITING },

    run: async (c) => {
      // A string that is not a code names no enrolment, which is the situation an answered one
      // is in — so it gets that situation's answer rather than a shape complaint.
      const userCode = readUserCode(c.req.valid('param').userCode)
      if (userCode === undefined) return refused(c, NOT_WAITING)

      const waiting = await enrolmentWaiting(db, userCode)
      if (waiting === undefined) return refused(c, NOT_WAITING)
      const existing = await existingMachinesFor(db, {
        ownerUserId: c.get('userId'),
        machineName: waiting.machineName,
      })

      return c.json(
        {
          machineName: waiting.machineName,
          expiresAt: waiting.expiresAt.toISOString(),
          existingMachines: existing.machines.map((machine) => ({
            id: machine.id,
            createdAt: machine.createdAt.toISOString(),
            presence: onTheWire(machine.whereabouts, existing.asOf),
          })),
        },
        200,
      )
    },
  })
}

/** Saying no, which is final: asking again under the same code will not change it. */
function refusing({ db }: EnrolmentApi) {
  return aPerson(db).post('/enrolments/{userCode}/refuse', {
    summary: 'Turn that machine away',
    params: { userCode: z.string() },
    answers: {
      204: 'It may not come in, and asking again will not change that',
      404: NOTHING_IS_WAITING,
    },

    run: async (c) => {
      const userCode = readUserCode(c.req.valid('param').userCode)
      if (userCode === undefined) return refused(c, NOT_WAITING)

      const answered = await refuseEnrolment(db, userCode)
      if (answered.kind === 'not-waiting') return refused(c, NOT_WAITING)

      return nothing(c, 204)
    },
  })
}

/**
 * Saying yes, which makes that machine yours.
 *
 * Answering normally adds a machine. When the person explicitly names an existing same-named
 * identity, it reconnects that one instead; a name alone never makes that decision. Its opposite,
 * `DELETE /me/machines/{id}`, is the standard method for taking one away.
 */
function approving({ db }: EnrolmentApi) {
  return aPerson(db).post('/me/machines', {
    summary: 'Say that machine is yours',
    body: LetItIn,
    answers: {
      204: 'It is yours',
      404: refuses(
        [NOT_WAITING, CANNOT_REPLACE],
        'Nothing is waiting, or that machine cannot be reconnected',
      ),
    },

    run: async (c) => {
      const approval = c.req.valid('json')
      const userCode = readUserCode(approval.userCode)
      if (userCode === undefined) return refused(c, NOT_WAITING)

      const userId = c.get('userId')
      const space =
        approval.spaceSlug === undefined
          ? undefined
          : (await spacesOf(db, userId)).find((one) => one.slug === approval.spaceSlug)
      if (approval.spaceSlug !== undefined && space === undefined) return refused(c, NOT_WAITING)

      const answered = await approveEnrolment(db, userCode, {
        userId,
        ...(approval.replaceMachineId === undefined
          ? {}
          : { replaceMachineId: approval.replaceMachineId }),
        ...(space === undefined ? {} : { approvedSpaceId: space.id }),
      })
      if (answered.kind === 'not-waiting') return refused(c, NOT_WAITING)
      if (answered.kind === 'cannot-replace') return refused(c, CANNOT_REPLACE)

      return nothing(c, 204)
    },
  })
}

/**
 * Saying yes in advance: an enrolment that arrives approved.
 *
 * Not a second mechanism. Somebody generating one has already made the decision the code path
 * asks a person to make — that the machine will be theirs — so the row is written with that
 * decision on it, and the machine that presents it skips only the waiting.
 *
 * Yours, like everything else about a machine. From Account it names only who made it; from a
 * Space's Add machine journey it also records that explicit destination. The key stays opaque to
 * the CLI either way, so a machine never chooses or enumerates Spaces.
 *
 * For a machine with no browser to open, which is most machines that are not somebody's laptop.
 */
function makingAKey({ db }: EnrolmentApi) {
  return aPerson(db).post('/me/machine-keys', {
    summary: 'Make a key a machine can come in with, without anybody approving it later',
    query: { space: z.string().optional() },
    answers: {
      201: sends(Key, 'The key, shown this once and never again'),
      404: NOTHING_IS_WAITING,
    },

    run: async (c) => {
      const secret = newEnrolmentSecret()
      const userId = c.get('userId')
      const askedSpace = c.req.valid('query').space
      const space =
        askedSpace === undefined
          ? undefined
          : (await spacesOf(db, userId)).find((one) => one.slug === askedSpace)
      if (askedSpace !== undefined && space === undefined) return refused(c, NOT_WAITING)

      // A key: no code and no machine name, because nobody will read one and nobody knows the
      // other yet. Which of those an enrolment has is the shape, not four fields left blank.
      const opened = await openEnrolment(db, {
        kind: 'key',
        secretHash: secret.hash,
        approvedBy: userId,
        ...(space === undefined ? {} : { approvedSpaceId: space.id }),
      })

      return c.json({ key: secret.secret, expiresAt: opened.expiresAt.toISOString() }, 201)
    },
  })
}
