/**
 * The S3-compatible edge of this process.
 *
 * Handover owns object keys and bytes; this file owns how those bytes cross the network. MinIO,
 * AWS S3, Cloudflare R2 and the other stores we are prepared to use all speak this protocol, so a
 * move between them changes deployment configuration and copies objects without changing a URL,
 * a database row, or a feature module.
 *
 * The contract is deliberately only what avatars consume now. Listing, presigning and deleting
 * would not make migration easier; they would be promises with nobody to keep them honest.
 */

import {
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
  S3ServiceException,
} from '@aws-sdk/client-s3'
import type { Env } from './env.ts'

export type StoredObject = {
  readonly bytes: Uint8Array
  readonly contentType: string
}

export type ObjectStore = {
  /** Absent is different from unreachable: only the first is permission to create the object. */
  readonly find: (key: string) => Promise<StoredObject | undefined>
  readonly put: (key: string, object: StoredObject) => Promise<void>
  /** The SDK owns sockets; the composition root closes them after requests have drained. */
  readonly close: () => void
}

type ObjectStoreEnv = Pick<
  Env,
  | 'OBJECT_STORE_ACCESS_KEY'
  | 'OBJECT_STORE_BUCKET'
  | 'OBJECT_STORE_ENDPOINT'
  | 'OBJECT_STORE_FORCE_PATH_STYLE'
  | 'OBJECT_STORE_REGION'
  | 'OBJECT_STORE_SECRET_KEY'
>

/**
 * Explicit credentials are for local S3-compatible stores. Without them the AWS SDK follows its
 * normal role chain, which is what production on AWS needs; inventing empty credentials here
 * would disable that chain and turn a valid deployment into one that can never authenticate.
 */
function explicitCredentials(env: ObjectStoreEnv) {
  if (env.OBJECT_STORE_ACCESS_KEY === undefined || env.OBJECT_STORE_SECRET_KEY === undefined) {
    return undefined
  }

  return {
    accessKeyId: env.OBJECT_STORE_ACCESS_KEY,
    secretAccessKey: env.OBJECT_STORE_SECRET_KEY,
  }
}

function isMissing(trouble: unknown): boolean {
  return trouble instanceof S3ServiceException && trouble.$metadata.httpStatusCode === 404
}

export function s3Objects(env: ObjectStoreEnv): ObjectStore {
  const credentials = explicitCredentials(env)
  const client = new S3Client({
    region: env.OBJECT_STORE_REGION,
    forcePathStyle: env.OBJECT_STORE_FORCE_PATH_STYLE,
    ...(env.OBJECT_STORE_ENDPOINT === undefined ? {} : { endpoint: env.OBJECT_STORE_ENDPOINT }),
    ...(credentials === undefined ? {} : { credentials }),
  })

  return {
    find: async (key) => {
      try {
        const found = await client.send(
          new GetObjectCommand({ Bucket: env.OBJECT_STORE_BUCKET, Key: key }),
        )
        if (found.Body === undefined) return undefined

        // Avatar SVGs are generated by this process and bounded to a few kilobytes. Buffering is
        // simpler and safer than leaking an SDK stream through the feature boundary; a future
        // consumer of large objects will need a different, streaming contract of its own.
        return {
          bytes: await found.Body.transformToByteArray(),
          contentType: found.ContentType ?? 'application/octet-stream',
        }
      } catch (trouble: unknown) {
        if (isMissing(trouble)) return undefined
        // A timeout is not absence. It may be an object we failed to read, and generating over it
        // on that answer would turn an unknown network result into a fact we do not know.
        throw trouble
      }
    },

    put: async (key, object) => {
      // If the response is lost, the caller fails this request and a retry reads the same key.
      // Both first writers produce identical bytes, so overwriting that key is idempotent.
      await client.send(
        new PutObjectCommand({
          Bucket: env.OBJECT_STORE_BUCKET,
          Key: key,
          Body: object.bytes,
          ContentType: object.contentType,
          CacheControl: 'public, max-age=31536000, immutable',
        }),
      )
    },

    close: () => {
      client.destroy()
    },
  }
}
